// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "test2":return img`
........................
........................
........22222...........
.......22222222.........
......22ddd22222........
.....222ddddd222........
.......dddddd2222.......
......2ddddddd222.......
......2ddddddd222.......
......2dddddd2222.......
......22ddddd2222.......
.....2222aaaa2222.......
.....2222aaaa22222......
.....222aaaaa22222......
.....22aaaaaa22222......
....22aaaaaaa22222......
....22aaaaaaa22222......
.....ccaaaaaa22222......
.....cccaaaaaa22c22.....
....ccccaaaaaaacc.......
...cccccaaaaaaaccc......
..cccccaaaaaaaaccc......
..dccc.aaaaaaaacccc.....
..ddc..aaaaaaaaacccd....
..dd...aaaaaaaaa.ccdd...
...d..aaaaaaaaaa..ddd...
......aaaaaaaaaa...dd...
......aaaaaaaaaaa.......
.......aaaaaaaaaa.......
........aaaaaaaaa.......
........aaaaaaccc.......
........caaaaaccc.......
........ccc...ccc.......
........ccc....ccc......
........ccc....ccc......
........ccc.....ccc.....
`;
            case "image1":
            case "test1":return img`
........................
........................
........99999...........
.......99999999.........
......99ddd99999........
.....999ddddd999........
.......dddddd9999.......
......9ddddddd999.......
......9ddddddd999.......
......9dddddd9999.......
......99ddddd9999.......
.....9999aaaa9999.......
.....9999aaaa99999......
.....999aaaaa99999......
.....99aaaaaa99999......
....99aaaaaaa99999......
....99aaaaaaa99999......
.....ccaaaaaa99999......
.....cccaaaaaa99c99.....
....ccccaaaaaaacc.......
...cccccaaaaaaaccc......
..cccccaaaaaaaaccc......
..dccc.aaaaaaaacccc.....
..ddc..aaaaaaaaacccd....
..dd...aaaaaaaaa.ccdd...
...d..aaaaaaaaaa..ddd...
......aaaaaaaaaa...dd...
......aaaaaaaaaaa.......
.......aaaaaaaaaa.......
........aaaaaaaaa.......
........aaaaaaccc.......
........caaaaaccc.......
........ccc...ccc.......
........ccc....ccc......
........ccc....ccc......
........ccc.....ccc.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
