// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "test":return img`
........................
........................
........99999...........
.......99999999.........
......99ddd99999........
.....999ddddd999........
.......dddddd9999.......
......9ddddddd999.......
......9ddddddd999.......
......9dddddd9999.......
......99ddddd9999.......
.....9999aaaa9999.......
.....9999aaaa99999......
.....999aaaaa99999......
.....99aaaaaa99999......
....99aaaaaaa99999......
....99aaaaaaa99999......
.....ccaaaaaa99999......
.....cccaaaaaa99c99.....
....ccccaaaaaaacc.......
...cccccaaaaaaaccc......
..cccccaaaaaaaaccc......
..dccc.aaaaaaaacccc.....
..ddc..aaaaaaaaacccd....
..dd...aaaaaaaaa.ccdd...
...d..aaaaaaaaaa..ddd...
......aaaaaaaaaa...dd...
......aaaaaaaaaaa.......
.......aaaaaaaaaa.......
........aaaaaaaaa.......
........aaaaaaccc.......
........caaaaaccc.......
........ccc...ccc.......
........ccc....ccc......
........ccc....ccc......
........ccc.....ccc.....
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
